# Generated by Django 5.1.2 on 2024-10-31 17:00

import api.common.helpers
import django.core.validators
import django.db.models.deletion
import functools
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advertiser',
            fields=[
                ('id', models.BigAutoField(help_text='Unique ID for each model instance, generated automatically.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this instance was created. Set automatically on creation.')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp when this instance was last updated. Automatically updated on each save.')),
                ('user_number', models.CharField(help_text='Identification number of the advertiser.', max_length=50)),
                ('nickname', models.CharField(help_text='Nickname of the advertiser.', max_length=50)),
                ('user_type', models.CharField(help_text='Type of advertiser (e.g., individual, company).', max_length=50)),
                ('month_finish_rate', models.DecimalField(decimal_places=4, help_text='Monthly transaction completion rate.', max_digits=5)),
                ('positive_rate', models.DecimalField(decimal_places=4, help_text='Percentage of positive feedback.', max_digits=5)),
                ('month_order_count', models.IntegerField(help_text='Number of orders completed in the month.')),
            ],
            options={
                'verbose_name': 'Entry with auto timestamps',
                'verbose_name_plural': 'Entries with auto timestamps',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BinanceTraderRequestLog',
            fields=[
                ('id', models.BigAutoField(help_text='Unique ID for each model instance, generated automatically.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this instance was created. Set automatically on creation.')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp when this instance was last updated. Automatically updated on each save.')),
                ('idempotency_token', models.CharField(default=functools.partial(api.common.helpers.generate_token, *(), **{'prefix': 'idmp', 'with_date': True}), help_text='Unique idempotency token for request uniqueness.', max_length=64, unique=True)),
                ('req_service_slug', models.CharField(choices=[('user_creation', 'user_creation'), ('transaction_creation', 'transaction_creation'), ('binance_price_check', 'binance_price_check'), ('binance_P2P_advertisement_search', 'binance_P2P_advertisement_search'), ('price_analysis', 'price_analysis'), ('notification_creation', 'notification_creation'), ('email_sending', 'email_sending')], help_text='Specifies the type of service request made.', max_length=40)),
                ('req_http_body', models.JSONField(blank=True, help_text='HTTP request body content, if applicable.', null=True)),
                ('res_http_body', models.JSONField(blank=True, help_text='HTTP response body content, if applicable.', null=True)),
                ('res_http_code', models.IntegerField(blank=True, help_text='HTTP status code from the response.', null=True)),
                ('res_result_message', models.CharField(blank=True, db_index=True, help_text='Detailed error or result message from the service.', max_length=255, null=True)),
                ('res_result_code', models.CharField(blank=True, help_text='Service response code, if available.', max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Entry with auto timestamps',
                'verbose_name_plural': 'Entries with auto timestamps',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(help_text='Unique ID for each model instance, generated automatically.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this instance was created. Set automatically on creation.')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp when this instance was last updated. Automatically updated on each save.')),
                ('name', models.CharField(help_text="User's full name.", max_length=60, validators=[django.core.validators.RegexValidator(message='Name must only contain letters, spaces, and underscores.', regex='^[\\w á-úÁ-Ú]*$'), django.core.validators.MinLengthValidator(2)])),
                ('email', models.EmailField(help_text='Unique email address used to identify the user.', max_length=254, unique=True)),
                ('user_token', models.CharField(default=functools.partial(api.common.helpers.generate_token, *(), **{'prefix': 'usr', 'with_date': True}), help_text='Unique token generated for the user.', max_length=128, unique=True)),
            ],
            options={
                'verbose_name': 'Entry with auto timestamps',
                'verbose_name_plural': 'Entries with auto timestamps',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(help_text='Unique ID for each model instance, generated automatically.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this instance was created. Set automatically on creation.')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp when this instance was last updated. Automatically updated on each save.')),
                ('ad_number', models.CharField(help_text='Unique identifier of the advertisement.', max_length=50)),
                ('trade_type', models.CharField(help_text='Type of trade (e.g., buy or sell).', max_length=50)),
                ('asset', models.CharField(help_text='Asset being traded (e.g., USDT).', max_length=50)),
                ('fiat_unit', models.CharField(help_text='Fiat currency used in the advertisement (e.g., USD).', max_length=10)),
                ('price', models.DecimalField(decimal_places=2, help_text='Price per unit of the asset.', max_digits=10)),
                ('min_trade_limit', models.DecimalField(decimal_places=2, help_text='Minimum trade limit.', max_digits=10)),
                ('max_trade_limit', models.DecimalField(decimal_places=2, help_text='Maximum trade limit.', max_digits=10)),
                ('advertiser', models.ForeignKey(help_text='Advertiser responsible for the advertisement.', on_delete=django.db.models.deletion.DO_NOTHING, related_name='advertisements', to='binance_trader_api.advertiser')),
            ],
            options={
                'verbose_name': 'Entry with auto timestamps',
                'verbose_name_plural': 'Entries with auto timestamps',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(help_text='Unique ID for each model instance, generated automatically.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this instance was created. Set automatically on creation.')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp when this instance was last updated. Automatically updated on each save.')),
                ('token_transaction', models.CharField(default=functools.partial(api.common.helpers.generate_token, *(), **{'prefix': 'trx', 'with_date': True}), help_text='Unique transaction token.', max_length=64, unique=True)),
                ('buy_price', models.DecimalField(decimal_places=2, help_text='Price at which the item was bought.', max_digits=10)),
                ('buy_date', models.DateTimeField(help_text='Date and time of purchase.')),
                ('target_profit_percent', models.DecimalField(decimal_places=2, help_text='Target profit percentage for the transaction (e.g., 15.00 for 15%).', max_digits=10, validators=[django.core.validators.MinValueValidator(0.01), django.core.validators.MaxValueValidator(100)])),
                ('notification_sent', models.DateTimeField(blank=True, help_text='Timestamp when notification was sent.', null=True)),
                ('status', models.CharField(choices=[('created', 'created'), ('pending', 'pending'), ('ready_to_sell', 'ready_to_sell'), ('completed', 'completed')], help_text='Current transaction status.', max_length=16)),
                ('advertisement', models.ForeignKey(blank=True, help_text='Associated advertisement for the transaction.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='transactions', to='binance_trader_api.advertisement')),
                ('user', models.ForeignKey(help_text='User who initiated the transaction.', on_delete=django.db.models.deletion.DO_NOTHING, related_name='transactions', to='binance_trader_api.user')),
            ],
            options={
                'verbose_name': 'Entry with auto timestamps',
                'verbose_name_plural': 'Entries with auto timestamps',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(help_text='Unique ID for each model instance, generated automatically.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this instance was created. Set automatically on creation.')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp when this instance was last updated. Automatically updated on each save.')),
                ('message', models.CharField(blank=True, help_text='Content of the notification message.', max_length=256, null=True)),
                ('notified_at', models.DateTimeField(help_text='Timestamp when notification was sent.')),
                ('transaction', models.ForeignKey(help_text='Transaction related to this notification.', on_delete=django.db.models.deletion.DO_NOTHING, related_name='notifications', to='binance_trader_api.transaction')),
                ('user', models.ForeignKey(help_text='User to be notified.', on_delete=django.db.models.deletion.DO_NOTHING, related_name='notifications', to='binance_trader_api.user')),
            ],
            options={
                'verbose_name': 'Entry with auto timestamps',
                'verbose_name_plural': 'Entries with auto timestamps',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
