# Generated by Django 5.1.2 on 2024-11-06 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binance_trader_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertiser',
            name='month_finish_rate',
            field=models.DecimalField(decimal_places=15, help_text='Monthly transaction completion rate.', max_digits=20),
        ),
        migrations.AlterField(
            model_name='advertiser',
            name='positive_rate',
            field=models.DecimalField(decimal_places=15, help_text='Percentage of positive feedback.', max_digits=20),
        ),
    ]
