# Generated by Django 5.1.2 on 2024-11-06 20:49

import api.common.helpers
import django.core.validators
import functools
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binance_trader_api', '0002_alter_advertiser_month_finish_rate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='max_trade_limit',
            field=models.DecimalField(decimal_places=2, help_text='Maximum trade limit.', max_digits=15),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='min_trade_limit',
            field=models.DecimalField(decimal_places=2, help_text='Minimum trade limit.', max_digits=15),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Price per unit of the asset.', max_digits=15),
        ),
        migrations.AlterField(
            model_name='advertiser',
            name='month_finish_rate',
            field=models.DecimalField(decimal_places=9, help_text='Monthly transaction completion rate.', max_digits=10, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='advertiser',
            name='month_order_count',
            field=models.PositiveIntegerField(help_text='Number of orders completed in the month.', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='advertiser',
            name='positive_rate',
            field=models.DecimalField(decimal_places=9, help_text='Percentage of positive feedback.', max_digits=10, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='binancetraderrequestlog',
            name='idempotency_token',
            field=models.CharField(default=functools.partial(api.common.helpers.generate_token, *(), **{'prefix': 'idmp', 'with_date': True}), help_text='Unique idempotency token for request uniqueness.', max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(help_text="User's full name.", max_length=60, validators=[django.core.validators.RegexValidator(regex='^[\\w á-úÁ-Ú]*$'), django.core.validators.MinLengthValidator(2)]),
        ),
    ]
