# Generated by Django 5.1.2 on 2024-11-07 18:33

import api.common.helpers
import django.core.validators
import functools
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binance_trader_api', '0003_alter_advertisement_max_trade_limit_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advertisement',
            options={},
        ),
        migrations.AlterModelOptions(
            name='advertiser',
            options={},
        ),
        migrations.AlterModelOptions(
            name='binancetraderrequestlog',
            options={},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='Automatically set when instance is created.'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='trade_type',
            field=models.CharField(choices=[('buy', 'buy'), ('sell', 'sell')], help_text='Type of trade (e.g., buy or sell).', max_length=50),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True, help_text='Automatically updated on each save.'),
        ),
        migrations.AlterField(
            model_name='advertiser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='Automatically set when instance is created.'),
        ),
        migrations.AlterField(
            model_name='advertiser',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='advertiser',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True, help_text='Automatically updated on each save.'),
        ),
        migrations.AlterField(
            model_name='advertiser',
            name='user_type',
            field=models.CharField(choices=[('individual', 'individual'), ('company', 'company')], help_text='Type of advertiser (e.g., individual, company).', max_length=50),
        ),
        migrations.AlterField(
            model_name='binancetraderrequestlog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='Automatically set when instance is created.'),
        ),
        migrations.AlterField(
            model_name='binancetraderrequestlog',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='binancetraderrequestlog',
            name='idempotency_token',
            field=models.CharField(default=functools.partial(api.common.helpers.generate_token, *(), **{'prefix': 'idmp', 'with_date': True}), help_text='Unique idempotency token for request uniqueness.', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='binancetraderrequestlog',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True, help_text='Automatically updated on each save.'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='Automatically set when instance is created.'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True, help_text='Automatically updated on each save.'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='Automatically set when instance is created.'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='target_profit_percent',
            field=models.DecimalField(decimal_places=2, help_text='Target profit percentage for the transaction (e.g., 15.00 for 15%).', max_digits=10, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='token_transaction',
            field=models.CharField(default=functools.partial(api.common.helpers.generate_token, *(), **{'prefix': 'trx', 'with_date': True}), help_text='Unique transaction token.', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True, help_text='Automatically updated on each save.'),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='Automatically set when instance is created.'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True, help_text='Automatically updated on each save.'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_token',
            field=models.CharField(default=functools.partial(api.common.helpers.generate_token, *(), **{'prefix': 'usr', 'with_date': True}), help_text='Unique token generated for the user.', max_length=50, unique=True),
        ),
    ]
