# Generated by Django 5.1.2 on 2024-11-07 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binance_trader_api', '0004_alter_advertisement_options_alter_advertiser_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertiser',
            name='user_type',
            field=models.CharField(choices=[('individual', 'Individual'), ('company', 'Company')], help_text='Type of advertiser (e.g., individual, company).', max_length=50),
        ),
    ]
