# Generated by Django 5.1.2 on 2024-11-07 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binance_trader_api', '0005_alter_advertiser_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertiser',
            name='user_type',
            field=models.CharField(choices=[('individual', 'individual'), ('company', 'company')], help_text='Type of advertiser (e.g., individual, company).', max_length=50),
        ),
    ]
