# Generated by Django 5.1.2 on 2024-11-18 22:27

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binance_trader_api', '0006_alter_advertiser_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='usdt_amount_buy',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Amount of USDT bought in the transaction.', max_digits=15, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
