services:
  web:
    image: binance_trader:dev
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: ["sh", "./scripts/entrypoint.sh"]
    command: ["sh", "./scripts/start"]
    volumes:
      - .:/API_PROJECTS
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - DJANGO_SETTINGS_MODULE=api.config.settings.base
      - PYTHONPATH=/API_PROJECTS/api
    depends_on:
      - db
      - redis
    networks:
      - binance_api_net

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h ${POSTGRES_DB_HOST} -p ${POSTGRES_DB_PORT} -U ${POSTGRES_DB_USER} || exit 1"]
      interval: 10s
      retries: 5
    stop_grace_period: 1m
    stop_signal: SIGINT
    networks:
      - binance_api_net

  redis:
    image: redis:alpine
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      retries: 10
      start_period: 30s
    networks:
      - binance_api_net

  celery:
    image: binance_trader_celery:dev
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A api.config.celery_setup worker --loglevel=info 
    volumes:
      - .:/API_PROJECTS
    depends_on:
      - redis
      - db
    env_file:
      - .env
    environment:
      - DJANGO_SETTINGS_MODULE=api.config.settings.base
      - PYTHONPATH=/API_PROJECTS/api
    networks:
      - binance_api_net
    stop_grace_period: 2m
    stop_signal: SIGINT

  celery-beat:
    image: binance_trader_celery_beat:dev
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A api.config.celery_setup beat --loglevel=info
    volumes:
      - .:/API_PROJECTS
    depends_on:
      - redis
      - db
    env_file:
      - .env
    environment:
      - DJANGO_SETTINGS_MODULE=api.config.settings.base
      - PYTHONPATH=/API_PROJECTS/api
    networks:
      - binance_api_net
    stop_grace_period: 2m
    stop_signal: SIGINT

volumes:
  postgres_data:

networks:
  binance_api_net:
    name: binance_api_net
    driver: bridge

