"""
Django settings for the API project.
Generated by 'django-admin startproject' using Django 4.2.11.
"""

import os
import tempfile
from pathlib import Path

from celery.schedules import crontab
from django.core.exceptions import ImproperlyConfigured

# Base directory of the project
BASE_DIR = Path(__file__).resolve().parent.parent

# Config logs
LOGS_DIR = Path(tempfile.gettempdir()) / "api_logs"
LOGS_DIR.mkdir(parents=True, exist_ok=True) if not LOGS_DIR.exists() else None


def getenvvar(name, default_value=None):
    """
    Retrieve an environment variable or raise an error if not defined.
    """

    value = os.environ.get(name, default_value)
    if value is None:
        raise ImproperlyConfigured(f"Environment variable {name} is undefined")
    return value


# Logging Configuration
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "file": {
            "level": "WARNING",
            "class": "logging.handlers.RotatingFileHandler",
            "filename": os.path.join(LOGS_DIR, "api.log"),
            "maxBytes": 5242880,  # 5 MB
            "backupCount": 10,  # Store up to 10 backup files
            "formatter": "detailed",
        },
        "console": {
            "level": "CRITICAL",
            "class": "logging.StreamHandler",
            "formatter": "simple",
        },
    },
    "formatters": {
        "detailed": {
            "format": "%(asctime)s %(name)s [%(levelname)s] %(message)s",
        },
        "simple": {
            "format": "%(levelname)s %(message)s",
        },
    },
    "loggers": {
        "": {
            "level": "WARNING",
            "handlers": ["file", "console"],
        },
    },
}

# Security Settings
SECRET_KEY = getenvvar("DJANGO_SECRET_KEY")
DEBUG = True
ALLOWED_HOSTS = getenvvar("DJANGO_ALLOWED_HOSTS", "").split(",") if getenvvar("DJANGO_ALLOWED_HOSTS", "") else []

# Application definition
INSTALLED_APPS = [
    # Django core apps
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # Third-party apps
    "django_celery_results",
    "django_celery_beat",
    "constance",
    "constance.backends.database",
    "rest_framework",
    # Local apps
    "binance_trader_api",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "api.config.urls"

# Templates Configuration
TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "api.config.wsgi.application"

# Database Configuration
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": getenvvar("POSTGRES_DB_NAME", "postgres"),
        "USER": getenvvar("POSTGRES_DB_USER", "postgres"),
        "PASSWORD": getenvvar("POSTGRES_DB_PASSWORD", "postgres"),
        "HOST": getenvvar("POSTGRES_DB_HOST", "db"),
        "PORT": getenvvar("POSTGRES_DB_PORT", "5432"),
        "CONN_MAX_AGE": 300,
    }
}

# Binance Trader API Database
if "BINANCE_TRADER_DB_NAME" in os.environ:
    DATABASES["binance_trader_api"] = {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": getenvvar("BINANCE_TRADER_API_DB_NAME"),
        "USER": getenvvar("BINANCE_TRADER_API_DB_USER"),
        "PASSWORD": getenvvar("BINANCE_TRADER_API_DB_PASSWORD"),
        "HOST": getenvvar("BINANCE_TRADER_API_DB_HOST"),
        "PORT": getenvvar("BINANCE_TRADER_API_DB_PORT"),
    }

# Password validation settings
AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": (
            "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"
        ),
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# Internationalization settings
LANGUAGE_CODE = "en-us"
TIME_ZONE = "UTC"
USE_I18N = True
USE_TZ = True


# Specifies the test runner to use for running tests.
TEST_RUNNER = "config.testing.DirBasedTestRunner"

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = "static/"

STATIC_ROOT = os.path.join(BASE_DIR, "static")
# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Celery Configuration
CELERY_BROKER_URL = getenvvar("CELERY_BROKER_URL", "redis://redis:6379/0")  # Redis URL
CELERY_RESULT_BACKEND = getenvvar(
    "django-db", "CELERY_RESULT_BACKEND"
)  # Django DB as result backend

# Celery broker connection retry settings
CELERY_BROKER_CONNECTION_MAX_RETRIES = int(
    getenvvar("CELERY_BROKER_CONNECTION_MAX_RETRIES", 5)
)
CELERY_BROKER_CONNECTION_TIMEOUT = int(
    getenvvar("CELERY_BROKER_CONNECTION_TIMEOUT", 30)
)

# Enable Eager mode for development (tasks run locally without a worker)
CELERY_TASK_ALWAYS_EAGER = getenvvar("CELERY_TASK_ALWAYS_EAGER", "False")

# Additional Celery settings
CELERY_RESULT_EXTENDED = True
CELERY_BEAT_SCHEDULER = "django_celery_beat.schedulers.DatabaseScheduler"
CELERY_TASK_TIME_LIMIT = int(
    getenvvar("CELERY_TASK_TIME_LIMIT", 300)
)  # Task timeout in seconds

CELERY_BEAT_SCHEDULE = {
    "check-price-task-every-5-minutes": {
        "task": "binance_trader_api.tasks.check_price_task",
        "schedule": crontab(minute="*/5"),  # every five minutes
    }
}

# Automatically discover tasks in the Binance Trader app
CELERY_IMPORTS = ("binance_trader_api.tasks",)

# External API Client Configuration
BINANCE_TRADER_API_REST_CLIENT = {
    "BASE_URL": getenvvar("BINANCE_TRADER_API_HOST"),
    "C2C_SEARCH_ENDPOINT": getenvvar("C2C_SEARCH_ENDPOINT"),
}

# Configuration for Constance Backend
CONSTANCE_BACKEND = "constance.backends.database.DatabaseBackend"

CONSTANCE_CONFIG = {
    "BINANCE_TRADER_API_REST_CLIENT_TIMEOUT_SECS": (
        10,
        "Timeout in seconds for a response of BinanceTrader services",
    ),
    "BINANCE_ROWS": (3, "Number of rows to retrieve in Binance API queries"),
    "BINANCE_PAYTYPES": (
        "BancolombiaSA,Nequi",
        "Payment types for Binance transactions, separated by commas",
    ),
    "BINANCE_FIAT": ("COP", "Fiat currency to use for Binance transactions"),
    "BINANCE_TRADE_TYPE": ("BUY", "Type of trade in Binance: BUY or SELL"),
    "BINANCE_ASSET": ("USDT", "Asset to trade in Binance (e.g., USDT)"),
    "BINANCE_FILTER_TYPE": ("all", "Filter type to apply in Binance"),
    "BINANCE_PUBLISHER_TYPE": (
        "merchant",
        "Publisher type in Binance (e.g., merchant)",
    ),
    "BINANCE_CLASSIFIES": (
        "mass,profession",
        "Classifications for Binance transactions, separated by commas",
    ),
    "BINANCE_TRADER_SLEEP_SECS": (
        5,
        "Time in seconds to wait between price monitoring requests",
    ),
}

# Email configuration using SMTP backend
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = os.getenv("EMAIL_HOST", "smtp.gmail.com")
EMAIL_PORT = os.getenv("EMAIL_PORT", 587)
EMAIL_USE_TLS = True
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD")
DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL")
